### ISSUE TITLE
remove EL5

### ISSUE THREAD

**Issue by b-harper** [chef-cookbooks/yum-ius#12]
Hey,

IUS will soon be [EOLing EL5][0] and el5 should be removed.

-Thanks

[0]: https://github.com/iuscommunity/announce/issues/4

**Comment by iennae** [comment]
Thanks for reporting. We'll get this sorted today.

**Comment by b-harper** [comment]
@iennae, thanks for the timely reply.  Let me know if you need any questions about IUS.

**Comment by iennae** [comment]
This has been merged in. Thanks again for reporting.
