### ISSUE TITLE
Using this cookbook in Amazon Linux

### ISSUE THREAD

**Issue by fabiendelpierre** [chef-cookbooks/yum-ius#5]
Hi there,
I'd like to use this cookbook to add the IUS repo in an Amazon Linux 2015.03 so I can install the `python33` package offered by IUS. I'm aware that the version of Amazon Linux I'm using adds a `python34` package but for now I'd like to stick with Python 3.3.x as a precaution for the compatibility of my app.

Anyway, if I just add `include_recipe "yum-ius::default"` to my recipe, the Chef run fails with the following output:
```
[2015-05-21T11:34:14-04:00] ERROR: yum_repository[ius] (yum-ius::default line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-ius] (/var/chef/cache/cookbooks/yum/providers/repository.rb line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of yum -q makecache --disablerepo=* --enablerepo=ius ----
STDOUT:
STDERR: One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: ius
---- End output of yum -q makecache --disablerepo=* --enablerepo=ius ----
Ran yum -q makecache --disablerepo=* --enablerepo=ius returned 1
```
FWIW, the `/etc/yum.repos.d/ius.repo` file does get created:
```
% cat ius.repo
# This file was generated by Chef
# Do NOT modify this file by hand.

[ius]
name=Ye Ole Rpm Repo
enabled=1
failovermethod=priority
gpgcheck=1
gpgkey=http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
sslverify=true
```

I'm guessing that the failure has to do with the `ius.repo` file missing a `mirrorlist=` line, but I only have vague theories as to why that is -- perhaps it's the IUS repo itself that's unable to support Amazon Linux, so the failure isn't really this cookbook's fault. 

So anyway, I wanted to ask if that's actually expected, i.e. if Amazon Linux is basically unsupported for one reason or another. If so, that's fine -- just wanted to see if anyone knew anything about this.

**Comment by yamad001** [comment]
I'm pretty sure it's because in [your_chef_root]/cookbooks/yum-ius/ius.rb there are these lines:
case node['platform']
when 'redhat'
  case node['platform_version'].to_i
  when 5
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-el5&arch=$basearch&protocol=http'
  when 6
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-el6&arch=$basearch&protocol=http'
  when 7
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-el7&arch=$basearch&protocol=http'
  end
else
  case node['platform_version'].to_i
  when 5
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-centos5&arch=$basearch&protocol=http'
  when 6
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-centos6&arch=$basearch&protocol=http'
  when 7
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-centos7&arch=$basearch&protocol=http'
  end
end

I believe Amazon Linux == 2015 (when using to_i), and hence the mirrorlist never gets added.
I think you can create an attribute like:
    default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-centos6&arch=$basearch&protocol=http'

so it will be defined.  Also, I've had to run (as mentioned by the chef README markdown file):
sudo yum clean metadata

Hope this helps.

**Comment by yamad001** [comment]
sorry typo the attribute added should be el6 like:
default['yum']['ius']['mirrorlist'] = 'https://mirrors.iuscommunity.org/mirrorlist/?repo=ius-el6&arch=$basearch&protocol=http'

**Comment by fabiendelpierre** [comment]
Thanks for the reply :) I'm past the point of caring now since I'm no longer using AWS or the IUS repo but hopefully this'll be useful to someone.

**Comment by tas50** [comment]
It doesn't appear the iUS support Amazon natively.  If someone wants to attempt to add it to this cookbook thats fine, but I wouldn't consider it a bug at the moment since upstream isn't supporting it.
