### ISSUE TITLE
Reversed behavior of ["managed"] attribute in v0.4.3

### ISSUE THREAD

**Issue by legal90** [chef-cookbooks/yum-ius#7]
Seems like v0.4.3 release should be revoked as soon as possible, because there is a broken behavior of `['yum-ius'][<repo_name>]['managed']` attributes.

Being set to `true`, this attribute means that the appropriate repo _should be managed_ by the recipe. But due to 9694d278b895bb8, this behavior have been reversed.

cc: @someara

**Comment by someara** [comment]
Sorry about that. Fixed up in 0.4.4
